### ISSUE TITLE
<style> catching up when you're already caught up

### ISSUE THREAD

**Issue by jake-stack** [saga-vcs/saga-excel#86] opened 2020-05-28 16:13 UTC
When I clicked catch-up and I was already caught-up, nothing appears in the task pane under the normal catch- up text. We should have a message that says "you're up to date!" or something like that.

**Comment by naterush** [comment] 2020-05-29 23:54
Duplicate of existing issue. Closing.

**Closed as completed by naterush** 2020-05-29 23:54 UTC
